/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classic;

public class App {

    public static void main(String[] args) {
        try {
            Class bar = Class.forName("foo.Bar");
            System.out.println(bar.getName() + " loaded from : " + bar.getProtectionDomain().getCodeSource().getLocation().toString());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
}
